---
title: "Employment and Wage Profile by Municipality and Industry"
author: Emanuelle Alemar
output: flexdashboard::flex_dashboard
runtime: shiny
---
    

```{r dat, include=FALSE}
require(shiny)
require(dplyr)
require(readr)
require(ggplot2)

# QCEW data

require(RCurl)
require(stringr)
require(readxl)
require(blsAPI)
require(scales)

masterdat = read.csv("Master QCEW Data R.csv", encoding = 'ASCII//TRANSLIT')

#source('qcew_data.R')


# employment aggregation
emp = aggregate(masterdat$annual_avg_emplvl ~ masterdat$year + masterdat$industry_title + masterdat$area_title, FUN = sum)
names(emp) = c('Year', 'Industry', 'Municipality', 'Employment')
all_munis = aggregate(masterdat$annual_avg_emplvl ~ masterdat$year +
                        masterdat$industry_title, FUN = sum)
all_industries = aggregate(masterdat$annual_avg_emplvl ~masterdat$year +
                             masterdat$area_title, FUN = sum)
all = aggregate(masterdat$annual_avg_emplvl ~ masterdat$year, FUN = sum)
emp = rbind(emp, data.frame("Year"=all_munis$`masterdat$year`, "Industry"=all_munis$`masterdat$industry_title`, "Municipality"=paste0('All Municipalities'), 'Employment'=all_munis$`masterdat$annual_avg_emplvl`))
emp = rbind(emp, data.frame("Year"=all_industries$`masterdat$year`, "Industry"=paste0('All Industries'), "Municipality"=all_industries$`masterdat$area_title`, "Employment"=all_industries$`masterdat$annual_avg_emplvl`))
emp = rbind(emp, data.frame('Year'=all$`masterdat$year`,
                            'Industry'=paste0('All Industries'), 'Municipality'=paste0('All Municipalities'), 'Employment'=all$`masterdat$annual_avg_emplvl`))


# establishments
estab = aggregate(masterdat$annual_avg_estabs ~ masterdat$year + masterdat$industry_title + masterdat$area_title, FUN = sum)
names(estab) = c('Year', 'Industry', 'Municipality', 'Establishments')
all_munis = aggregate(masterdat$annual_avg_estabs ~ masterdat$year +
                        masterdat$industry_title, FUN = sum)
all_industries = aggregate(masterdat$annual_avg_estabs ~masterdat$year +
                             masterdat$area_title, FUN = sum)
all = aggregate(masterdat$annual_avg_estabs ~ masterdat$year, FUN = sum)
estab = rbind(estab, data.frame("Year"=all_munis$`masterdat$year`, "Industry"=all_munis$`masterdat$industry_title`, "Municipality"=paste0('All Municipalities'), 'Establishments'=all_munis$`masterdat$annual_avg_estabs`))
estab = rbind(estab, data.frame("Year"=all_industries$`masterdat$year`, "Industry"=paste0('All Industries'), "Municipality"=all_industries$`masterdat$area_title`, "Establishments"=all_industries$`masterdat$annual_avg_estabs`))
estab = rbind(estab, data.frame('Year'=all$`masterdat$year`,
                            'Industry'=paste0('All Industries'), 'Municipality'=paste0('All Municipalities'), 'Establishments'=all$`masterdat$annual_avg_estabs`))

# wages
wage = aggregate(masterdat$total_annual_wages ~ masterdat$year + masterdat$industry_title + masterdat$area_title, FUN = sum)
names(wage) = c('Year', 'Industry', 'Municipality', 'Wages')
all_munis = aggregate(masterdat$total_annual_wages ~ masterdat$year +
                        masterdat$industry_title, FUN = sum)
all_industries = aggregate(masterdat$total_annual_wages ~masterdat$year +
                             masterdat$area_title, FUN = sum)
all = aggregate(masterdat$total_annual_wages ~ masterdat$year, FUN = sum)
wage = rbind(wage, data.frame("Year"=all_munis$`masterdat$year`, "Industry"=all_munis$`masterdat$industry_title`, "Municipality"=paste0('All Municipalities'), 'Wages'=all_munis$`masterdat$total_annual_wages`))
wage = rbind(wage, data.frame("Year"=all_industries$`masterdat$year`, "Industry"=paste0('All Industries'), "Municipality"=all_industries$`masterdat$area_title`, "Wages"=all_industries$`masterdat$total_annual_wages`))
wage = rbind(wage, data.frame('Year'=all$`masterdat$year`,
                                'Industry'=paste0('All Industries'), 'Municipality'=paste0('All Municipalities'), 'Wages'=all$`masterdat$total_annual_wages`))
```
    
Details and Sources {.sidebar data-width=300}
-------------------------------------

This dashboard was created using the shiny package in the R programming language. The main source of the data feeding this dashboard is the Quartery Census of Employment and Wages, produced by the Bureau of Labor Statistics (BLS). The data is extracted from the BLS Application User Interface (API) using the R package blsQCEW, and it is aggregated at the County, Supersector level. The documentation for the program that extracts the data and for this dashboard can be found at github.com/ealemar8. 

```{r}
selectInput('muni', label = 'Choose a Municipality',
            choices = sort(emp$Municipality), selected = 'All Municipalities')
selectInput('industry', label = 'Choose an Industry',
            choices = sort(emp$Industry, decreasing = T), selected = 'All Industries')
```


Column
-------------------------------------

### Annual Employment 
    
```{r}
renderPlot({
  ggplot(data = emp[emp$Municipality==input$muni&emp$Industry==input$industry, ], 
         aes(x = Year, y = Employment)) +
    geom_line() +
    geom_text(data = emp[emp$Municipality==input$muni&emp$Industry==input$industry, ], aes(y = Employment, label = as.character(Employment))) + ggtitle(paste0('Persons employed in ', input$muni, ' - ', input$industry)) 
})
```
   
Column
-------------------------------------

### Annual Establishments

```{r}
renderPlot({
  ggplot(data = estab[estab$Municipality==input$muni&estab$Industry==input$industry, ], 
         aes(x = Year, y = Establishments)) +
    geom_line() +
    geom_text(data = estab[estab$Municipality==input$muni&estab$Industry==input$industry, ], aes(y = Establishments, label = as.character(round(Establishments, 2)))) + ggtitle(paste0('Establishments in ', input$muni,' - ', input$industry)) 
})
```
    
    
Column
-------------------------------------

### Annual Wages

```{r}
renderPlot({
  ggplot(data = wage[wage$Municipality==input$muni&wage$Industry==input$industry, ], 
         aes(x = Year, y = Wages)) +
    geom_line() +
    geom_text(data = wage[wage$Municipality==input$muni&wage$Industry==input$industry, ], aes(y = Wages, label = dollar(Wages, scale = 0.000001, suffix='M'))) + ggtitle(paste0('Wages in ', input$muni, ' - ', input$industry))  
})
```






